# Generated by Django 4.2.7 on 2024-09-12 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("asset", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Allarm",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=1000)),
                ("price", models.CharField(max_length=1000)),
                ("up_or_downe", models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name="Currrency",
        ),
    ]
