# Generated by Django 4.2.7 on 2024-09-12 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("asset", "0002_allarm_delete_currrency"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Allarm",
            new_name="Alarm",
        ),
    ]
